In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
y = [1,2,3,4,5]

In [3]:
type(x)
np.ndarray
x.ndim

1

In [4]:
x = np.array([[1,2],[2,3]])
x.ndim

2

In [5]:
x = np.array([[[1,2],[2,3]]
              ,[[3,4],[4,5]]])
x.ndim
x.shape

(2, 2, 2)

In [6]:
x.size

8

In [7]:
x.dtype

dtype('int32')

In [8]:
x = [1,2,3,4]
y = np.array([1,2,3,4])

In [9]:
import sys
sys.getsizeof(x)

88

In [10]:
y.itemsize * y.size

16

In [11]:
x = [1,2,3,4,5]
y = [6,7,8,9,10]
x * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [18]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
x + (1)

array([2, 3, 4, 5, 6])

In [13]:
import time
x = np.random.random(20)
y = np.random.random(20)
a = list(x)
b = list(y)
res = []
st_time = time.time();
for i in range(len(a)):
    res.append(a[i]*b[i]);
end_time = time.time();
print(end_time-st_time)
print(x*y)

0.0
[0.15964903 0.00278995 0.2416299  0.39496654 0.03574755 0.3098682
 0.14271405 0.3507209  0.03412062 0.3692043  0.00904774 0.30227216
 0.24137417 0.41243024 0.35565753 0.00390678 0.45427074 0.28657509
 0.00283261 0.01217692]


In [15]:
x = np.zeros(3)
x = np.ones(3)
x = np.identity((3))
x = np.arange(0,11,2)
x = np.linspace(10,20,5)
#check the arguments to be passed in the above for the inclusion/exclusion of certain value
x = np.random.random((3))
f = list(x)
x

In [19]:
x = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
x.shape
x

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [115]:
x[0:,2:3,0:]
#slicing practice kar

array([[[ 5,  6]],

       [[11, 12]],

       [[17, 18]]])

In [20]:
x.flatten(order = 'c')
# x.flatten(order = 'f')
#np.insert
#np.append
#np.delete
#np.unique
#axis parameter
#

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])